### ISSUE TITLE
Modify the body of a request after initialization before executing it

### ISSUE THREAD

**Issue by nashfive** [immobiliare/RealHTTP#26]
Hi! That's an awesome library :) 
I am trying to find a replacement to my verbose Moya/Alamofire layer and I came across RealHTTP that works pretty well!
I am just trying to see what would be the best approach to intercept a request and mutate the request body. For example, I'd like to send URL encoded forms, and have an interceptor that would add some extra data on top on the initial ones. 

Since `req.body` is a `Data`, the `req.urlRequestModifier` is not very helpful in this case :( 
Any idea ? 
Or should I resort to defer the creation of the HttpRequest at the very last step and pass a Dictionary around ?

**Comment by malcommac** [comment]
Hi @nashfive , thank you!
I've considered an interceptor to change only the body but it seems a bit constrained and probably someone, in the future, may also need to change other parameters before the execution of the request.  
You can, however, change the body as you wish, just create and use it or cast the `body` of the request to your desired type or create the 

## Example 1: Create the type

Consider the multipart form; you can create form from any point of your code. Just use:

```swift
        let form = HTTPBody.MultipartForm()

        // somewhere add p1
        form.add(string: "value", name: "p1")
```

Before executing the call just set the body:

```swift
req.body = form
```
  
## Example 2: Use Casting

Another example is to cast the `body` to your desidered type.  
To simplify this behaviour I've added (commit above) the following shortcuts (you will find it in 1.3.0+):

- `asData` and `asString` to cast `body` to `Data` and `String`
- `asFormURLEncoded` to cast `body` to `WWWFormURLEncodedBody`
- `asMultipartForm` to cast `body` to `MultipartForm`
- `asStream` to cast `body` to `asStream`

and use the object to modify the content itself.  
Consider the following example with form

```swift
let req = HTTPRequest {
  $0.url = URL(string: "https://somedomain.com")
  $0.method = .post
  $0.body = .multipart {
    // configure multipart
  }
}
```

then use `asMultipartForm` to cast and add your own additional params:

```swift
req.body.asMultipartForm?.add(string: "value 2", name: "p2")
```

For your specific issue consider the following init:

```swift
let req = HTTPRequest {
   $0.body = .formURLEncodedBody(["username": "Michael Bublé", "pwd": "abc"])
}
```

You can add or remove values:

```swift
req.body.asFormURLEncoded?.set(value: "newValue", forKey: "newKey")
req.body.asFormURLEncoded?.removeValueForKey("newKey")
```

**Comment by nashfive** [comment]
Thanks for your feedback @malcommac ! 
I guess my use case is too specific, as usually interceptors usually updates the headers to add a token, or mutate the query parameters. 
Anyway, I'll have a look at these new shortcuts in your 1.3.0 release ;)
