### ISSUE TITLE
HTTPAltRequestValidator fetches 401, but original request is not repeated

### ISSUE THREAD

**Issue by haemi** [immobiliare/RealHTTP#27]
Thanks for this awesome library, would love to use it in production!

The problem I'm currently facing is that when my original request returns a 401, the `HTTPAltRequestValidator` works as expected (i.e. it does the login call and sets it on the client), but my original request is not repeated as I see in a proxy running on my mac.

this is my request:

```
HTTPRequest {
                $0.url = URL(string: "https://...")
                $0.maxRetries = 3
                $0.method = .get
            }
```

and this is my setup:

```
        let client = HTTPClient.shared

        let authValidator = HTTPAltRequestValidator(statusCodes: [.unauthorized]) { request, response in
            // If triggered here you'll specify the alt call to execute in order to refresh a JWT session token
            // before any retry of the initial failed request.
            return try! Endpoint.login("...", "...").httpRequest()
        } onReceiveAltResponse: { request, response in
            // Once you have received response from your `refreshToken` call
            // you can do anything you need to use it.
            // In this example we'll set the global client's authorization header.
            if let authorizationHeader = response.headers[.authorization] {
                client.headers.set(.authorization, authorizationHeader)
            }
        }

        client.validators.insert(authValidator, at: 0)
```

I get to the the `client.headers.set(.authorization, authorizationHeader)` - but then the original request is not repeated... what am I missing here?

Thanks a lot for your help!

**Comment by malcommac** [comment]
Hi @haemi, you're right, there was a bug with the `HTTPAltRequestValidator` which can't perform the retry mechanism. 

I've solved it in https://github.com/immobiliare/RealHTTP/commit/8bbe0fb9a4d95a8fafc1f1c77f68c0c3a9611720 while the https://github.com/immobiliare/RealHTTP/commit/45cea68e41fbfabb55ef903dadbff7ab7f879a82 introduces several unit tests for the validator itself.

I'll release it shortly.

**Comment by haemi** [comment]
Hi @malcommac , AWESOME!

With the new branch `.package(name: "RealHTTP", url: "https://github.com/immobiliare/RealHTTP.git", branch: "fix/27-alt-validator"),` my test just turned green, thanks a lot!

<img width="196" alt="image" src="https://user-images.githubusercontent.com/183958/159117028-9843a08b-828d-41d6-8c1c-d9fc35014d52.png">
