### ISSUE TITLE
Allow request retry with custom HTTP codes (like 429 - Too Many Requests) and implement delay retry

### ISSUE THREAD

**Issue by tciuro** [immobiliare/RealHTTP#3]
| Q                   | A      |
| ------------------- | ------ |
| BC Break            | no |
| Version             | 0.9.15  |

### Support Question

When a service returns `HTTP 429 Too Many Requests`, I was expecting RealHTTP to trigger the retry mechanism. Alas, this is not what I see. I get an `HTTP 429` error right away without any retries. Shouldn't this scenario be handled by RealHTTP? 🤔

**Comment by malcommac** [comment]
Hi @tciuro,
In fact the current implementation of the `HTTPDefaultValidator` does not implement a way to retry based on HTTP status code. However is pretty simple to implement it and I think it could be useful.
So I've added it to the main repository and I'll push a new release.

Currently `HTTPDefaultValidator` exposes a new property:
- `retriableHTTPStatusCodes`: it defines a list of `HTTPStatusCode` which can trigger a retry of the call; it's a dictionaryw where the value is a `TimeInterval` (0 means retry immediately, a positive value like 2 means 2 seconds after retry).

Default implementation set `.tooManyRequests`'s http status code with 3 seconds interval.  
You can however set it as you need by modifying the client's `HTTPDefaultValidator` or provide your own subclass.

This is an example which works with the default shared `HTTPClient` but you can use it with your own instance.

```swift
let myValidator = HTTPDefaultValidator()
myValidator.retriableHTTPStatusCodes = [.tooManyRequests: 5] // wait 5 seconds for HTTP 429
HTTPClient.shared.validators = [myValidator]
        
request.maxRetries = 2 // you must set a retry > 1 in order to get it works
request.onRawResponse { response in
  // do something
}
request.run()
```

It will be part of the 0.9.16 version.
