### ISSUE TITLE
'HTTPStubResponse' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by haemi** [immobiliare/RealHTTP#31]
I wanted to implement a dynamic stubbing in the way that I fetch an ID from the request and according to that return the JSON of locally stored files, e.g.

https://www.example.com/something/1234/foo/bar => returns 1234.json

For that I tried to use the example of the [dynamic matcher](https://github.com/immobiliare/RealHTTP/blob/main/Documentation/7.Stubber.md#dynamic-matcher), but the compiler complains `'HTTPStubResponse' initializer is inaccessible due to 'internal' protection level`.

**Comment by malcommac** [comment]
merged and released in 1.3.1. Thanks 💯
