### ISSUE TITLE
Custom error is returned from custom validator and/or decode() function

### ISSUE THREAD

**Issue by haemi** [immobiliare/RealHTTP#34]
I have a custom validator like this:

```swift
public class ErrorMessageValidator: HTTPValidator {

    public func validate(response: HTTPResponse, forRequest request: HTTPRequest) -> HTTPResponseValidatorResult {
        if [HTTPStatusCode.ResponseType.success, .redirection].contains(response.statusCode.responseType) {
            return .nextValidator
        }

        guard let data = response.data else {
            return .failChain(HTTPError(.invalidResponse))
        }

        let jsonData = JSON(data)

        guard let message = jsonData.dictionary?["message"]?.string else {
            return .nextValidator
        }

        return .failChain(MyError(title: message))
    }
}
```

And I get to the last line as expected, so a `MyError` is returned, wrapped into the `failChain`.

But in my calling code:

```swift
let request = myServerCall(myParameters).httpRequest()
let response = try await request.fetch(MyModel.self)
```

an error is thrown (expected) but it is an `HTTPError` with an empty `error` property, so my `MyError` isn't available here

**Comment by malcommac** [comment]
May you post the structure of `MyError` so I can replicate the error? Thanks!

**Comment by haemi** [comment]
it's very simple struct:

```
public struct MyError: Error {
    public let title: String

    public init(title: String) {
        self.title = title
    }
}
```

**Comment by malcommac** [comment]
Okay I've fixed the dispatch of custom errors. Moreover I decided to dispatch original response of the request and attach additional error information based upon the library activity (max attempts, validation errors etc.).  
May you take a look to see if it works for you?
I've also added two dedicated unit tests.

**Comment by haemi** [comment]
it works when I use

```
let response = try await request.fetch()
// now, response.error?.error is MyError
```

but when I use

```
let myModel = try await request.fetch(MyModel.self)
```

the error isn't thrown if the body can be encoded. I would have expected that somehow I get to the error then as well, but there's no way as `myModel` is of type `MyModel`. Currently it's only possible to do it in multiple steps:

```
let response = try await request.fetch()
// check if response.error?.error is set, if not:
let myModel = try response.decode(MyModel.self)
```

**Comment by malcommac** [comment]
You are absolutely right, the fetch error should be passed outside the `decode()` function.
However the error must be an `HTTPError` so you would read it as:

```swift
do {
  _ = try await req.fetch(client: newClient, DummyDecodeStruct.self)
} catch {
  let customUnderlyingError = (error as? HTTPError)?.error as? MyError
  print(customUnderlyingError)
}
```

**Comment by malcommac** [comment]
ok I've fixed the code and added the necessary unit test
