### ISSUE TITLE
HTTPClient's queryParams are not added to requests that have no query parameters (aka nil)

### ISSUE THREAD

**Issue by nashfive** [immobiliare/RealHTTP#35]
Hi I've noticed that even if I set a bunch of query parameters on my HTTPClient instance, they are not added on the requests that don't have query parameters (i.e. `request.queryItems` is nil, not an empty dict) :

In `HTTPRequest.swift` line 536,  if `newComps.queryItems` is nil, then the `.append(contentsOf:)` will not occur.
```swift
if let commonQueryParams = client?.queryParams, commonQueryParams.isEmpty == false {
    newComp.queryItems?.append(contentsOf: commonQueryParams)
 }
 ```
Not sure if it's an expected behaviour or a bug 🤔  

Feel free to close this issue directly if this is intentional 😉

**Comment by malcommac** [comment]
Hi @nashfive , it was an issue. I've fixed it and added related unit test. I'll release it with 1.3.2.
