### ISSUE TITLE
Cannot run example code

### ISSUE THREAD

**Issue by X901** [immobiliare/RealHTTP#51]
I tried your example , but I get error

> Instance method 'fetch' requires that 'HTTPRequest' conform to 'APIResourceConvertible'"

That error appeared hear

```
public extension HTTPClient {
func fetch<T: APIResourceConvertible>(_ convertible: T) async throws -> T.Result {
let result = try await fetch(convertible.request())
return try result.decode(T.Result.self)
}
}
```

**Comment by ilai1823** [comment]
@X901 just specify the module as shown below:
`public extension HTTPClient {
    func fetch<T: APIResourceConvertible>(_ convertible: T) async throws -> T.Result {
        let result = try await **RealHTTP.**fetch(convertible.request())
        return try result.decode(T.Result.self)
    }
}`

**Comment by malcommac** [comment]
thanks for your support @NicFontana
