### ISSUE TITLE
isAbsoluteURL regex doesn't work like expected

### ISSUE THREAD

**Issue by PoissonBallon** [immobiliare/RealHTTP#54]
### Bug Report

| Q                   | A      |
| ------------------- | ------ |
| BC Break            | no |
| Version             | 1.52  |

#### Summary
isAbsoluteURL regex doesn't work like expected

#### Current behavior

Impossible to add urlComponents.queryItems coz path is absolute :/ 

#### How to reproduce

`/connect/login` is an absolute URL 
`connect/login` is an absolute URL 

#### Expected behavior

`/connect/login` is not an absolute URL 
`connect/login` is not an absolute URL 

I think error is the `?` after the first group in the regex

**Comment by malcommac** [comment]
Thank you for your report, I've added a new regular expression validated using `NSRegularExpression` and several tests.

**Comment by PoissonBallon** [comment]
Thanks for your awesome works !!!
