### ISSUE TITLE
HTTPDataLoader crashes decrementStrong on line 438

### ISSUE THREAD

**Issue by hschouman** [immobiliare/RealHTTP#58]
### Bug Report

| Q                   | A      |
| ------------------- | ------ |
| BC Break            | no |
| Version             | 1.5.2  |

#### Summary

Hello, I am experiencing some crash using RealHTTP on my app. Not sure if it comes from the lib or the use I do.

#### Current behavior

The app crash when deallocating a pointer on line 438 of the file HTTPDataLoader.swift.

#### How to reproduce

2% of my users are experiencing the crash but not sure of how to reproduce for the moment.

Here are the stack trace : [crash.txt](https://github.com/immobiliare/RealHTTP/files/9191294/crash.txt)
<img width="1169" alt="Capture d’écran 2022-07-26 à 17 45 34" src="https://user-images.githubusercontent.com/8625118/181050879-443449d5-9a23-472b-bae6-103417e2366c.png">

Thanks for your help

**Comment by malcommac** [comment]
On line 438 of HTTPDataLoader on version 1.5.2 there is [the following line](https://github.com/immobiliare/RealHTTP/blob/12c5e2d21f34ee5fa1036a354e8e5bc2db5bf561/Sources/RealHTTP/Client/Internal/HTTPDataLoader/HTTPDataLoader.swift#L438).

Of course we should call client's delegate to main thread:

```swift
if let client = self.client {
            client.delegate?.client(client, didFinish: (handler.request, task), response: response)
        }
```

However, it should be not your issue. Have you found a way to replicate this issue? Did you perform some action in your `HTTPClient`'s `delegate` object for that event?

**Comment by hschouman** [comment]
Not found a way to replicate yet. Yes we use the delegate object for that event to forward the `request.task`,`response.error?.error` and `response.data` to Datadog methods : `URLSessionInterceptor.shared?.taskCompleted(task: task, error: error)` and `URLSessionInterceptor.shared?.taskReceivedData(task: task, data: data)`.

Also with Xcode beta I have two warnings that are not here with Xcode 13.4.1, that could be related :
<img width="1157" alt="Capture d’écran 2022-08-16 à 15 10 04" src="https://user-images.githubusercontent.com/8625118/184887564-d3e26c00-6750-4fc3-a9a1-4fd5ad90afce.png">

**Comment by malcommac** [comment]
The warning should be okay with the fixes on main branch where events to delegate are sent in main thread. 
May you have a look and test it?
