### ISSUE TITLE
SPM Bug: Xcode 134.1 100 % CPU usage with SwiftLintPlugin enabled

### ISSUE THREAD

**Issue by Kondamon** [immobiliare/RealHTTP#60]
### Platform Version

Any

### SDK Version

1.7.0

### Xcode Version

13.4.1 (13F100)

### Steps To Reproduce

Embed the latest 1.7.0 in any bigger project and run project.

Xcode has over 100% usage as soon as the play button is being hit. Also restart of Xcode with project or restart of Mac and opening the project leads to 100% CPU usage. Xcode is extremely slow and doesn't show errors in the code anymore.

### Expected Behavior

Version not affecting Xcode CPU usage.

### Actual Incorrect Behavior

100% CPU usage when SDK is embedded in project.

**Comment by Kondamon** [comment]
Possibly related to [swift.org forum](https://forums.swift.org/t/spm-plugin-with-binary-target-high-cpu-usage/59535) , introduced with https://github.com/immobiliare/RealHTTP/commit/ed1187b22e072e1087fcd177ef569ab0b9d4485d .

**Comment by nashfive** [comment]
Hmm.. could it be caused by the 1.7.0 addition of the SwiftLintXcode in the project ?

**Comment by nashfive** [comment]
@malcommac I was wondering if it was possible to do a 1.6.3 release with only the bugfixes that you've integrated in the 1.7.0?

**Comment by malcommac** [comment]
I'll release a major later tomorrow, temporarily disabling the plug-in until a fix is out (or most likely Xcode 14 became the de facto choice)

**Comment by malcommac** [comment]
Released. I'll keep an eye on this bug in order to find a fix or workaround. Thanks for reporting.
