### ISSUE TITLE
[Bug]: HTTP Stubbing: URL matcher incorrectly strips port when using "ignore query parameters" option

### ISSUE THREAD

**Issue by aetherealtech** [immobiliare/RealHTTP#70]
### Platform Version

iOS 16.1

### SDK Version

1.4.0

### Xcode Version

Xcode 14.1

### Steps To Reproduce

Run the following code:

```swift
let stub = HTTPStubRequest()
  match(URL: URL(string: "http://localhost:3001/some/path")!)
  .stub(for: .get) { _, _ in
    let response = HTTPStubResponse()
    response.statusCode = .ok
    return response
}
        
let matches = stub.matchers[0].matches(request: URLRequest(url: URL(string: "http://localhost:3001/some/path")!), for: stub)
```

Note that `matches` should be `true`, but it is `false`.

This is because the `.ignoreQueryParameters` option results in the port getting stripped from the URL.  The code that does that is in Foundation+Extension.swift:

```swift
// Returns the base URL string build with the scheme, host and path.
/// For example:
/// "https://www.apple.com/v1/test?param=test"
/// would be "https://www.apple.com/v1/test"
public var baseString: String? {
  guard let scheme = scheme, let host = host else { return nil }
  return scheme + "://" + host + path
}
```

This strips the query parameters as expected, but `host` doesn't include the port, so the resulting URL is also stripped of the port.

The above example returns `true` for `matches` if the ports are removed from the URLs.

### Expected Behavior

URL matching should work as expected for URLs with manually specified ports, when the `.ignoreQueryParameters` option is enabled.

### Actual Incorrect Behavior

URLs fail to match even if they are exactly the same if `.ignoreQueryParameters` is enabled and the URLs contain explicit ports.

**Comment by malcommac** [comment]
thank you for your report. we have fixed it in 1.8.0.
